# Stage 1: Builder
FROM python:3.12-alpine AS builder

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    git \
    curl \
    postgresql-dev

COPY requirements/base.txt requirements/dev.txt requirements/git.txt ./

RUN pip install --user --no-cache-dir --no-deps -r git.txt && \
    pip install --user --no-cache-dir -r base.txt -r dev.txt

# Stage 2: Tiny runtime image
FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache \
    postgresql-client \
    curl \
    libpq

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

COPY config*.yaml ./
COPY main.py ./
RUN if [ -f .env ]; then cp .env .; else echo "No .env file, continuing..."; fi
COPY utils/ ./utils/
COPY types_lib/ ./types_lib/
COPY server/ ./server/
COPY models/ ./models/
COPY migrations/ ./migrations/
COPY i18n/ ./i18n/

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

EXPOSE 50051

CMD ["python", "main.py"]
