INSERT INTO
  permissions (id, name, description, category)
VALUES
  (
    'profile_view',
    'authentication.permissions.profile_view.name',
    'authentication.permissions.profile_view.description',
    'account'
  ),
  (
    'profile_edit',
    'authentication.permissions.profile_edit.name',
    'authentication.permissions.profile_edit.description',
    'account'
  ),
  (
    'password_update',
    'authentication.permissions.password_update.name',
    'authentication.permissions.password_update.description',
    'account'
  ),
  (
    'account_delete',
    'authentication.permissions.account_delete.name',
    'authentication.permissions.account_delete.description',
    'account'
  ),
  (
    'preferences_set',
    'authentication.permissions.preferences_set.name',
    'authentication.permissions.preferences_set.description',
    'account'
  ),
  (
    'order_place',
    'authentication.permissions.order_place.name',
    'authentication.permissions.order_place.description',
    'orders'
  ),
  (
    'order_cancel',
    'authentication.permissions.order_cancel.name',
    'authentication.permissions.order_cancel.description',
    'orders'
  ),
  (
    'order_track',
    'authentication.permissions.order_track.name',
    'authentication.permissions.order_track.description',
    'orders'
  ),
  (
    'order_history_view',
    'authentication.permissions.order_history_view.name',
    'authentication.permissions.order_history_view.description',
    'orders'
  ),
  (
    'card_add',
    'authentication.permissions.card_add.name',
    'authentication.permissions.card_add.description',
    'payments'
  ),
  (
    'card_remove',
    'authentication.permissions.card_remove.name',
    'authentication.permissions.card_remove.description',
    'payments'
  ),
  (
    'transactions_view',
    'authentication.permissions.transactions_view.name',
    'authentication.permissions.transactions_view.description',
    'payments'
  ),
  (
    'coupons_apply',
    'authentication.permissions.coupons_apply.name',
    'authentication.permissions.coupons_apply.description',
    'payments'
  ),
  (
    'wallet_save',
    'authentication.permissions.wallet_save.name',
    'authentication.permissions.wallet_save.description',
    'payments'
  ),
  (
    'review_write',
    'authentication.permissions.review_write.name',
    'authentication.permissions.review_write.description',
    'reviews'
  ),
  (
    'product_rate',
    'authentication.permissions.product_rate.name',
    'authentication.permissions.product_rate.description',
    'reviews'
  ),
  (
    'wishlist_add',
    'authentication.permissions.wishlist_add.name',
    'authentication.permissions.wishlist_add.description',
    'wishlist'
  ),
  (
    'wishlist_remove',
    'authentication.permissions.wishlist_remove.name',
    'authentication.permissions.wishlist_remove.description',
    'wishlist'
  ),
  (
    'wishlist_view',
    'authentication.permissions.wishlist_view.name',
    'authentication.permissions.wishlist_view.description',
    'wishlist'
  ),
  (
    'suppliers_follow',
    'authentication.permissions.suppliers_follow.name',
    'authentication.permissions.suppliers_follow.description',
    'wishlist'
  ),
  (
    'ticket_create',
    'authentication.permissions.ticket_create.name',
    'authentication.permissions.ticket_create.description',
    'support'
  ),
  (
    'ticket_history_view',
    'authentication.permissions.ticket_history_view.name',
    'authentication.permissions.ticket_history_view.description',
    'support'
  ),
  (
    'ticket_close',
    'authentication.permissions.ticket_close.name',
    'authentication.permissions.ticket_close.description',
    'support'
  ),
  (
    'order_return',
    'authentication.permissions.order_return.name',
    'authentication.permissions.order_return.description',
    'orders'
  ),
  (
    'return_priority',
    'authentication.permissions.return_priority.name',
    'authentication.permissions.return_priority.description',
    'orders'
  ),
  (
    'deliveries_scheduled',
    'authentication.permissions.deliveries_scheduled.name',
    'authentication.permissions.deliveries_scheduled.description',
    'orders'
  ),
  (
    'rewards_cashback',
    'authentication.permissions.rewards_cashback.name',
    'authentication.permissions.rewards_cashback.description',
    'payments'
  ),
  (
    'checkout_one_click',
    'authentication.permissions.checkout_one_click.name',
    'authentication.permissions.checkout_one_click.description',
    'payments'
  ),
  (
    'review_edit',
    'authentication.permissions.review_edit.name',
    'authentication.permissions.review_edit.description',
    'reviews'
  ),
  (
    'review_delete',
    'authentication.permissions.review_delete.name',
    'authentication.permissions.review_delete.description',
    'reviews'
  ),
  (
    'review_report',
    'authentication.permissions.review_report.name',
    'authentication.permissions.review_report.description',
    'reviews'
  ),
  (
    'reviewer_power_badge',
    'authentication.permissions.reviewer_power_badge.name',
    'authentication.permissions.reviewer_power_badge.description',
    'reviews'
  ),
  (
    'wishlist_share',
    'authentication.permissions.wishlist_share.name',
    'authentication.permissions.wishlist_share.description',
    'wishlist'
  ),
  (
    'tags_follow',
    'authentication.permissions.tags_follow.name',
    'authentication.permissions.tags_follow.description',
    'wishlist'
  ),
  (
    'notifications_restock',
    'authentication.permissions.notifications_restock.name',
    'authentication.permissions.notifications_restock.description',
    'wishlist'
  ),
  (
    'agent_chat',
    'authentication.permissions.agent_chat.name',
    'authentication.permissions.agent_chat.description',
    'support'
  ),
  (
    'support_priority',
    'authentication.permissions.support_priority.name',
    'authentication.permissions.support_priority.description',
    'support'
  ),
  (
    'alerts_price_drop',
    'authentication.permissions.alerts_price_drop.name',
    'authentication.permissions.alerts_price_drop.description',
    'market_awareness'
  ),
  (
    'alerts_restock',
    'authentication.permissions.alerts_restock.name',
    'authentication.permissions.alerts_restock.description',
    'market_awareness'
  ),
  (
    'ordering_bulk',
    'authentication.permissions.ordering_bulk.name',
    'authentication.permissions.ordering_bulk.description',
    'orders'
  ),
  (
    'order_approval_workflows',
    'authentication.permissions.order_approval_workflows.name',
    'authentication.permissions.order_approval_workflows.description',
    'orders'
  ),
  (
    'payments_invoice',
    'authentication.permissions.payments_invoice.name',
    'authentication.permissions.payments_invoice.description',
    'payments'
  ),
  (
    'terms_net',
    'authentication.permissions.terms_net.name',
    'authentication.permissions.terms_net.description',
    'payments'
  ),
  (
    'pricing_custom',
    'authentication.permissions.pricing_custom.name',
    'authentication.permissions.pricing_custom.description',
    'payments'
  ),
  (
    'trends_market_realtime',
    'authentication.permissions.trends_market_realtime.name',
    'authentication.permissions.trends_market_realtime.description',
    'market_awareness'
  ),
  (
    'reports_category_performance',
    'authentication.permissions.reports_category_performance.name',
    'authentication.permissions.reports_category_performance.description',
    'market_awareness'
  ),
  (
    'tracking_product_lifecycle',
    'authentication.permissions.tracking_product_lifecycle.name',
    'authentication.permissions.tracking_product_lifecycle.description',
    'market_awareness'
  ),
  (
    'tracking_competitor_product',
    'authentication.permissions.tracking_competitor_product.name',
    'authentication.permissions.tracking_competitor_product.description',
    'market_awareness'
  ),
  (
    'accounts_multi_user',
    'authentication.permissions.accounts_multi_user.name',
    'authentication.permissions.accounts_multi_user.description',
    'org_tools'
  ),
  (
    'access_role_based_control',
    'authentication.permissions.access_role_based_control.name',
    'authentication.permissions.access_role_based_control.description',
    'org_tools'
  ),
  (
    'dashboard_org',
    'authentication.permissions.dashboard_org.name',
    'authentication.permissions.dashboard_org.description',
    'org_tools'
  ),
  (
    'logs_audit',
    'authentication.permissions.logs_audit.name',
    'authentication.permissions.logs_audit.description',
    'org_tools'
  ),
  (
    'auth_sso',
    'authentication.permissions.auth_sso.name',
    'authentication.permissions.auth_sso.description',
    'org_tools'
  ),
  (
    'access_secure_api',
    'authentication.permissions.access_secure_api.name',
    'authentication.permissions.access_secure_api.description',
    'org_tools'
  ),
  (
    'account_manager_dedicated',
    'authentication.permissions.account_manager_dedicated.name',
    'authentication.permissions.account_manager_dedicated.description',
    'support'
  );
