INSERT INTO
  public.tags (id, name)
VALUES
  (1, 'printer'),
  (2, 'dollhouse'),
  (3, 'fashion boots'),
  (4, 'instant noodles'),
  (5, 'seat cover'),
  (6, 'hair dryer'),
  (7, 'craft kit'),
  (8, 'leather jacket'),
  (9, 'graphics card'),
  (10, 'camping stove'),
  (11, 'puzzle'),
  (12, 'evening gown'),
  (13, 'laminator'),
  (14, 'cutlery set'),
  (15, 'dog collar'),
  (16, 'wristwatch'),
  (17, 'kayak'),
  (18, 'LED headlights'),
  (19, 'summer dress'),
  (20, 'dash cam'),
  (21, 'tire inflator'),
  (22, 'sportswear'),
  (23, 'baking mix'),
  (24, 'storage rack'),
  (25, 'electric shaver'),
  (26, 'cat litter'),
  (27, 'pet shampoo'),
  (28, 'car charger'),
  (29, 'yoga mat'),
  (30, 'stapler'),
  (31, 'conditioner'),
  (32, 'train set'),
  (33, 'beard trimmer'),
  (34, 'tent'),
  (35, 'jeans'),
  (36, 'remote control car'),
  (37, 'tablet'),
  (38, 'tea bags'),
  (39, 'bluetooth speaker'),
  (40, 'scarf'),
  (41, 'notebook'),
  (42, 'smartwatch'),
  (43, 'moisturizer'),
  (44, 'chocolate bar'),
  (45, 'windshield wiper'),
  (46, 'treadmill'),
  (47, 'noise cancelling'),
  (48, 'dumbbells'),
  (49, 'floor mat'),
  (50, 'vacuum cleaner'),
  (51, 'face cream'),
  (52, 'office chair'),
  (53, 'sneakers'),
  (54, 'non-stick pan'),
  (55, 'hamster wheel'),
  (56, 'play tent'),
  (57, 'bedding'),
  (58, 'car wax'),
  (59, 'laptop'),
  (60, '4K TV'),
  (61, 'chess set'),
  (62, 'CPU'),
  (63, 'coffee maker'),
  (64, 'snack box'),
  (65, 'body lotion'),
  (66, 'sticky notes'),
  (67, 'building blocks'),
  (68, 'pet bed'),
  (69, 'running belt'),
  (70, 'facial serum'),
  (71, 'backpack'),
  (72, 'blender'),
  (73, 'dishwasher'),
  (74, 'engine oil'),
  (75, 'eyeliner'),
  (76, 'pasta'),
  (77, 'action figure'),
  (78, 'sunglasses'),
  (79, 'power bank'),
  (80, 'hot sauce'),
  (81, 'dog food'),
  (82, 'coffee beans'),
  (83, 'training pad'),
  (84, 'bird cage'),
  (85, 'wallet'),
  (86, 'ballpoint pen'),
  (87, 'gaming mouse'),
  (88, 'bicycle helmet'),
  (89, 'dried fruits'),
  (90, 'olive oil'),
  (91, 'mechanical pencil'),
  (92, 'water bottle'),
  (93, 'fishing rod'),
  (94, 'hiking boots'),
  (95, 'dining table'),
  (96, 'nail polish'),
  (97, 'dog leash'),
  (98, 'whiteboard'),
  (99, 'shampoo'),
  (100, 'microwave oven'),
  (101, 'desk organizer'),
  (102, 'golf clubs'),
  (103, 'file cabinet'),
  (104, 'perfume'),
  (105, 'eraser'),
  (106, 'lipstick'),
  (107, 'sunscreen'),
  (108, 'board game'),
  (109, 'smartphone'),
  (110, 'formal shirt'),
  (111, 'mattress'),
  (112, 'car vacuum'),
  (113, 'monitor'),
  (114, 'handbag'),
  (115, 'lego set'),
  (116, 'casual wear'),
  (117, 'breakfast cereal'),
  (118, 'educational toy'),
  (119, 'home theater'),
  (120, 'organic honey'),
  (121, 'paper shredder'),
  (122, 'cat toy'),
  (123, 'running shoes'),
  (124, 'GPS tracker'),
  (125, 'sofa set'),
  (126, 'sleeping bag'),
  (127, 'wireless charger'),
  (128, 'air fryer'),
  (129, 'steering wheel cover'),
  (130, 'aquarium filter');
