CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(26) PRIMARY KEY,
  user_id VARCHAR NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  subcategory VARCHAR(255) NOT NULL,
  has_variations BOOLEAN NOT NULL,
  brand_name VARCHAR(256),
  has_brand_name BOOLEAN NOT NULL,
  product_id VARCHAR(24),
  has_product_id BOOLEAN NOT NULL,
  product_id_type VARCHAR(5),
  description TEXT NOT NULL,
  bullet_points JSONB NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  fulfillment_type VARCHAR(24) NOT NULL,
  processing_time INTEGER NOT NULL,
  details JSONB NOT NULL,
  media JSONB NOT NULL,
  offer JSONB NOT NULL,
  safety JSONB NOT NULL,
  tags JSONB NOT NULL,
  metadata JSONB,
  ar_enabled BOOLEAN DEFAULT FALSE,
  slug TEXT NOT NULL,
  status VARCHAR(64) NOT NULL,
  version SMALLINT NOT NULL DEFAULT 1,
  schema_version SMALLINT NOT NULL,
  created_at BIGINT NOT NULL,
  published_at BIGINT,
  updated_at BIGINT,
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX products_offer_gin_idx ON products USING gin (offer);
